<a href="https://colab.research.google.com/github/Somrat390/Deep-Learning/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.11.0+cpu'

# Creating Scaler Tensor

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler2 = torch.tensor(7,8)
scaler2

TypeError: tensor() takes 1 positional argument but 2 were given

In [7]:
scaler2 = torch.tensor([7,8]) # this become a vector
scaler2, scaler2.ndim

(tensor([7, 8]), 1)

### dimention checking

In [3]:
scaler.ndim

0

#### retrive value from tensor as a interger

In [8]:
scaler.item()

7

# Vector

#### A vector is a single dimension tensor but can contain many numbers.

In [9]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

# Matrix

In [14]:
Matrix = torch.tensor([[4,5],
                       [8,9]])
Matrix

tensor([[4, 5],
        [8, 9]])

In [15]:
Matrix.ndim

2

In [17]:
Matrix.shape

torch.Size([2, 2])

# Tensor

In [19]:
Tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
Tensor.ndim

3

In [21]:
Tensor.shape

torch.Size([1, 3, 3])

# Random tensor

In [23]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.0009, 0.8235, 0.1380, 0.4635],
        [0.3000, 0.2102, 0.3210, 0.3172],
        [0.6501, 0.5749, 0.0368, 0.2315]])

In [24]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor, random_image_size_tensor.ndim, random_image_size_tensor.shape

(tensor([[[0.2640, 0.7662, 0.3153],
          [0.7776, 0.7264, 0.0450],
          [0.2074, 0.3426, 0.0291],
          ...,
          [0.3164, 0.3243, 0.7047],
          [0.4228, 0.5817, 0.4639],
          [0.6580, 0.9328, 0.8499]],
 
         [[0.9055, 0.5689, 0.9013],
          [0.2369, 0.3144, 0.0200],
          [0.8852, 0.8637, 0.6050],
          ...,
          [0.5657, 0.7225, 0.9635],
          [0.9710, 0.7966, 0.4315],
          [0.3206, 0.4913, 0.2031]],
 
         [[0.5952, 0.9385, 0.7398],
          [0.8796, 0.4288, 0.4362],
          [0.8489, 0.8055, 0.6518],
          ...,
          [0.1117, 0.3145, 0.2571],
          [0.3277, 0.4507, 0.7144],
          [0.2026, 0.0256, 0.2233]],
 
         ...,
 
         [[0.9451, 0.0257, 0.5317],
          [0.0029, 0.0760, 0.5817],
          [0.6576, 0.0381, 0.9641],
          ...,
          [0.3506, 0.9050, 0.9216],
          [0.3212, 0.1168, 0.4680],
          [0.5831, 0.7372, 0.9451]],
 
         [[0.9525, 0.9246, 0.1040],
          [0

# Zero and One

In [26]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [28]:
One = torch.ones(size=(3,4))
One, One.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Range

In [29]:
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_ones = torch.ones_like(zero_to_ten)
ten_ones, ten_zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [31]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py'>

In [32]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [33]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16