<a href="https://colab.research.google.com/github/Somrat390/Deep-Learning/blob/main/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.11.0+cpu'

# Creating Scaler Tensor

In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler2 = torch.tensor(7,8)
scaler2

TypeError: tensor() takes 1 positional argument but 2 were given

In [ ]:
scaler2 = torch.tensor([7,8]) # this become a vector
scaler2, scaler2.ndim

(tensor([7, 8]), 1)

### dimention checking

In [ ]:
scaler.ndim

0

#### retrive value from tensor as a interger

In [ ]:
scaler.item()

7

# Vector

#### A vector is a single dimension tensor but can contain many numbers.

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

# Matrix

In [ ]:
Matrix = torch.tensor([[4,5],
                       [8,9]])
Matrix

tensor([[4, 5],
        [8, 9]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([2, 2])

# Tensor

In [ ]:
Tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

# Random tensor

In [ ]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.0009, 0.8235, 0.1380, 0.4635],
        [0.3000, 0.2102, 0.3210, 0.3172],
        [0.6501, 0.5749, 0.0368, 0.2315]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor, random_image_size_tensor.ndim, random_image_size_tensor.shape

(tensor([[[0.2640, 0.7662, 0.3153],
          [0.7776, 0.7264, 0.0450],
          [0.2074, 0.3426, 0.0291],
          ...,
          [0.3164, 0.3243, 0.7047],
          [0.4228, 0.5817, 0.4639],
          [0.6580, 0.9328, 0.8499]],
 
         [[0.9055, 0.5689, 0.9013],
          [0.2369, 0.3144, 0.0200],
          [0.8852, 0.8637, 0.6050],
          ...,
          [0.5657, 0.7225, 0.9635],
          [0.9710, 0.7966, 0.4315],
          [0.3206, 0.4913, 0.2031]],
 
         [[0.5952, 0.9385, 0.7398],
          [0.8796, 0.4288, 0.4362],
          [0.8489, 0.8055, 0.6518],
          ...,
          [0.1117, 0.3145, 0.2571],
          [0.3277, 0.4507, 0.7144],
          [0.2026, 0.0256, 0.2233]],
 
         ...,
 
         [[0.9451, 0.0257, 0.5317],
          [0.0029, 0.0760, 0.5817],
          [0.6576, 0.0381, 0.9641],
          ...,
          [0.3506, 0.9050, 0.9216],
          [0.3212, 0.1168, 0.4680],
          [0.5831, 0.7372, 0.9451]],
 
         [[0.9525, 0.9246, 0.1040],
          [0

# Zero and One

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
One = torch.ones(size=(3,4))
One, One.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Range

In [ ]:
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_ones = torch.ones_like(zero_to_ten)
ten_ones, ten_zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [ ]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py'>

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

# Getting information from the tensor

In [ ]:
tensor = torch.rand(size=(3,4))

In [ ]:
tensor

tensor([[0.9394, 0.4403, 0.3517, 0.9640],
        [0.2824, 0.8208, 0.0238, 0.4827],
        [0.1809, 0.1250, 0.1088, 0.5137]])

In [ ]:
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


# Tensor Operation

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 5

tensor([ 5, 10, 15])

In [ ]:
tensor - 5

tensor([-4, -3, -2])

In [ ]:
tensor * 100

tensor([100, 200, 300])

In [ ]:
torch.mul(tensor ,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.sub(tensor,5)

tensor([-4, -3, -2])

# Matrix Multiplication

#### Element wise Multiplication

In [ ]:
tensor * tensor

tensor([1, 4, 9])

# Matrix Multiplication

In [ ]:
tensor.matmul(tensor)

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2,3],
            [4,5,6],
            [7,8,9]])

tensor_B = torch.tensor([[3,4,5],
            [4,5,6],
            [3,4,2]])

In [ ]:
output = torch.matmul(tensor_A, tensor_B.T)

In [ ]:
output

tensor([[ 26,  32,  17],
        [ 62,  77,  44],
        [ 98, 122,  71]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 26,  32,  17],
        [ 62,  77,  44],
        [ 98, 122,  71]])

In [ ]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3,out_features=6)

x = tensor_A.float()
output = linear(x)

print(x.shape)
print(output.shape)
print(output)

torch.Size([3, 3])
torch.Size([3, 6])
tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [3.0806, 2.3351, 3.3587, 1.3955, 3.5330, 2.7943],
        [5.4366, 3.8962, 5.0596, 1.9545, 5.8824, 4.1410]],
       grad_fn=<AddmmBackward0>)


# Aggreation

Find the max,min,mean,sum

In [5]:
tensor = torch.arange(0,100,10).float()
tensor

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [6]:
print(f'Minimum: {tensor.min()}')
print(f'Maximum: {tensor.max()}')
print(f'Mean: {tensor.mean()}')
print(f'Sum : {tensor.sum()}')

Minimum: 0.0
Maximum: 90.0
Mean: 45.0
Sum : 450.0


# Find the index of minimum and maximum index

In [7]:
x  = torch.arange(1,80,15)
x

tensor([ 1, 16, 31, 46, 61, 76])

In [9]:
print(x.argmax())
print(x.argmin())

tensor(5)
tensor(0)


# Change Data type

In [10]:
tensor = torch.arange(10.,100.,10)
tensor.dtype

torch.float32

In [11]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16



tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [14]:
tensor_8 = tensor.type(torch.int8)
tensor_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


# Reshaping, stacking, squeezing and unsqueezing

In [17]:
x = torch.arange(1.,8.,1)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

#### Reshape the x with a new dimention

In [19]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

#### We can also change the view with torch.view()
Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too

In [20]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [21]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

## If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack()

In [26]:
torch.stack([x,x,x,x,x],dim=1)

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.]])

In [25]:
torch.stack([x,x,x,x],dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

####
How about removing all single dimensions from a tensor?

To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1)

In [32]:
z = x_reshaped.squeeze()
z, z.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [34]:
x = z.unsqueeze(dim=0)
x, x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [35]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing

In [36]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [37]:
print(f"first square bracket {x[0]}")
print(f"Second square bracket {x[0][0]}")
print(f"third square bracket {x[0][0][0]}")

first square bracket tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket tensor([1, 2, 3])
third square bracket 1


In [38]:
x[:,0]

tensor([[1, 2, 3]])

In [39]:
x[:,:,0]

tensor([[1, 4, 7]])

In [40]:
x[:,1]

tensor([[4, 5, 6]])

# Numpy to Tensor

In [43]:
import numpy as np
array = np.arange(1,10,2)
numpy_to_tensor = torch.from_numpy(array).type(torch.float32)
numpy_to_tensor

tensor([1., 3., 5., 7., 9.])

In [46]:
tensor_to_numpy = numpy_to_tensor.numpy().astype(int)
tensor_to_numpy

array([1, 3, 5, 7, 9])

# Stooping the randomness if two tensor

In [48]:
import random

random_seed = 42
torch.manual_seed(seed = random_seed)
random_torch_C = torch.rand(size=(3,4))


torch.manual_seed(seed = random_seed)
random_torch_D = torch.rand(size=(3,4))

random_torch_C, random_torch_D, random_torch_C == random_torch_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [1]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [2]:
import tensorflow as tf
import timeit

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise SystemError('GPU device not found')

def cpu():
  with tf.device('/cpu:0'):
    random_image_cpu = tf.random.normal((100, 100, 100, 3))
    net_cpu = tf.keras.layers.Conv2D(32, 7)(random_image_cpu)
    return tf.math.reduce_sum(net_cpu)

def gpu():
  with tf.device('/device:GPU:0'):
    random_image_gpu = tf.random.normal((100, 100, 100, 3))
    net_gpu = tf.keras.layers.Conv2D(32, 7)(random_image_gpu)
    return tf.math.reduce_sum(net_gpu)

# We run each op once to warm up; see: https://stackoverflow.com/a/45067900
cpu()
gpu()

# Run the op several times.
print('Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images '
      '(batch x height x width x channel). Sum of ten runs.')
print('CPU (s):')
cpu_time = timeit.timeit('cpu()', number=10, setup="from __main__ import cpu")
print(cpu_time)
print('GPU (s):')
gpu_time = timeit.timeit('gpu()', number=10, setup="from __main__ import gpu")
print(gpu_time)

Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
4.603653806000011
GPU (s):
0.13882640500003163


In [3]:
!nvidia-smi

Fri Jul 17 07:44:59 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P0             26W /   70W |    1211MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
torch.cuda.is_available()

True

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'