In [5]:
import torch
torch.__version__

'2.9.0+cpu'

In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.dim()

0

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scaler.item()

7

In [ ]:
# Vector
number = torch.tensor([1,2,3,4])
number

tensor([1, 2, 3, 4])

In [ ]:
number.dim()

1

In [ ]:
number.item()

RuntimeError: a Tensor with 4 elements cannot be converted to Scalar

In [ ]:
number = torch.tensor(7,8,9)

TypeError: tensor() takes 1 positional argument but 3 were given

In [ ]:
number.shape   # tell the how many numbers in the vector

torch.Size([4])

# Matrix

In [ ]:
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.dim()

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

## In matix.shape[0] means In matrix we have 2 row and 3 column.

# Tensor

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR .dim()

3

In [ ]:
TENSOR .shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR1 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]],[[1,2,3],[4,5,6],[7,8,9]])
TENSOR1

TypeError: tensor() takes 1 positional argument but 2 were given

# Random Tensor

In [ ]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1821, 0.8254, 0.1282, 0.9254],
         [0.2625, 0.1522, 0.9507, 0.0499],
         [0.8126, 0.9804, 0.1918, 0.7214]]),
 torch.float32)

In [6]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[0.4174, 0.2894, 0.7941],
         [0.1993, 0.0947, 0.1102],
         [0.9641, 0.4100, 0.5133],
         ...,
         [0.3393, 0.3224, 0.1934],
         [0.6880, 0.9497, 0.0590],
         [0.8661, 0.0801, 0.5347]],

        [[0.3398, 0.6200, 0.7761],
         [0.2939, 0.0143, 0.5113],
         [0.8005, 0.4370, 0.5955],
         ...,
         [0.7881, 0.2606, 0.1167],
         [0.8795, 0.6343, 0.0049],
         [0.9305, 0.4267, 0.1916]],

        [[0.7644, 0.6863, 0.9277],
         [0.8699, 0.3242, 0.3658],
         [0.8577, 0.6558, 0.2798],
         ...,
         [0.8700, 0.4596, 0.0259],
         [0.8649, 0.4034, 0.3764],
         [0.3961, 0.4755, 0.5542]],

        ...,

        [[0.1050, 0.3053, 0.0894],
         [0.2909, 0.2813, 0.3563],
         [0.6305, 0.8452, 0.1587],
         ...,
         [0.5943, 0.7754, 0.4125],
         [0.1618, 0.8381, 0.4310],
         [0.6532, 0.6166, 0.8915]],

        [[0.0879, 0.3844, 0.3991],
         [0.9387, 0.9973, 0.1089],
         [0.

In [7]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and One Tensor

In [8]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Tensor Range

In [16]:
zero_to_one = torch.range(start=0,end=10,step=1).type(torch.int32)
zero_to_one, zero_to_one.dtype

/tmp/ipython-input-3897185000.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_one = torch.range(start=0,end=10,step=1).type(torch.int32)


(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32),
 torch.int32)

### Another tensor with same shape with one tensor

In [13]:
ten_zeros = torch.zeros_like(input=zero_to_one)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

In [14]:
ten_one = torch.ones_like(input=zero_to_one)
ten_one

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)

In [17]:
float32_tensor = torch.tensor([3,4,6],dtype=None,device=None,requires_grad=False)
float32_tensor.shape, float32_tensor.device

(torch.Size([3]), device(type='cpu'))