In [ ]:
import torch

In [ ]:
some_tansor = torch.rand(3,4)
some_tansor

tensor([[0.4568, 0.0526, 0.1945, 0.7713],
        [0.6957, 0.4647, 0.8148, 0.6562],
        [0.9619, 0.8929, 0.3741, 0.5944]])

In [ ]:
some_tansor.shape

torch.Size([3, 4])

In [ ]:
some_tansor.dtype, some_tansor.device

(torch.float32, device(type='cpu'))

# Tensor Manipulation

In [ ]:
new_tansor = torch.tensor([1,2,3])
new_tansor + 10

tensor([11, 12, 13])

In [ ]:
new_tansor

tensor([1, 2, 3])

In [ ]:
new_tansor = new_tansor + 10
new_tansor

tensor([11, 12, 13])

In [ ]:
new_tansor * 10

tensor([110, 120, 130])

In [ ]:
new_tansor

tensor([11, 12, 13])

In [ ]:
new_tansor - 10

tensor([1, 2, 3])

In [ ]:
torch.multiply(new_tansor,10)

tensor([110, 120, 130])

In [ ]:
new_tansor

tensor([11, 12, 13])

# Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)