In [ ]:
import torch

In [ ]:
some_tansor = torch.rand(3,4)
some_tansor

tensor([[0.4568, 0.0526, 0.1945, 0.7713],
        [0.6957, 0.4647, 0.8148, 0.6562],
        [0.9619, 0.8929, 0.3741, 0.5944]])

In [ ]:
some_tansor.shape

torch.Size([3, 4])

In [ ]:
some_tansor.dtype, some_tansor.device

(torch.float32, device(type='cpu'))

# Tensor Manipulation

In [ ]:
new_tansor = torch.tensor([1,2,3])
new_tansor + 10

tensor([11, 12, 13])

In [ ]:
new_tansor

tensor([1, 2, 3])

In [ ]:
new_tansor = new_tansor + 10
new_tansor

tensor([11, 12, 13])

In [ ]:
new_tansor * 10

tensor([110, 120, 130])

In [ ]:
new_tansor

tensor([11, 12, 13])

In [ ]:
new_tansor - 10

tensor([1, 2, 3])

In [ ]:
torch.multiply(new_tansor,10)

tensor([110, 120, 130])

In [ ]:
new_tansor

tensor([11, 12, 13])

# Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [7]:
import torch
import random

random_seed = 20
torch.manual_seed(seed=random_seed)
tensor_C = torch.rand(3,4)

torch.random.manual_seed(seed=random_seed)
tensor_D = torch.rand(3,4)
print(f"Tensor C:\n{tensor_C}\n")
print(f"Tensor D:\n{tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
tensor_C == tensor_D

Tensor C:
tensor([[0.5615, 0.1774, 0.8147, 0.3295],
        [0.2319, 0.7832, 0.8544, 0.1012],
        [0.1877, 0.9310, 0.0899, 0.3156]])

Tensor D:
tensor([[0.5615, 0.1774, 0.8147, 0.3295],
        [0.2319, 0.7832, 0.8544, 0.1012],
        [0.1877, 0.9310, 0.0899, 0.3156]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [8]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
!nvidia-smi

Tue Feb 10 04:45:54 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   69C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
print(torch.cuda.is_available())


True


In [3]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [4]:
import tensorflow as tf
import timeit

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise SystemError('GPU device not found')

def cpu():
  with tf.device('/cpu:0'):
    random_image_cpu = tf.random.normal((100, 100, 100, 3))
    net_cpu = tf.keras.layers.Conv2D(32, 7)(random_image_cpu)
    return tf.math.reduce_sum(net_cpu)

def gpu():
  with tf.device('/device:GPU:0'):
    random_image_gpu = tf.random.normal((100, 100, 100, 3))
    net_gpu = tf.keras.layers.Conv2D(32, 7)(random_image_gpu)
    return tf.math.reduce_sum(net_gpu)

# We run each op once to warm up; see: https://stackoverflow.com/a/45067900
cpu()
gpu()

# Run the op several times.
print('Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images '
      '(batch x height x width x channel). Sum of ten runs.')
print('CPU (s):')
cpu_time = timeit.timeit('cpu()', number=10, setup="from __main__ import cpu")
print(cpu_time)
print('GPU (s):')
gpu_time = timeit.timeit('gpu()', number=10, setup="from __main__ import gpu")
print(gpu_time)
print('GPU speedup over CPU: {}x'.format(int(cpu_time/gpu_time)))

Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
3.8369636829999934
GPU (s):
0.14360441299999138
GPU speedup over CPU: 26x


In [5]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

In [7]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [8]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')